<?php
// echo "DoctorsPropertyValuesTable";

namespace Otus\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Otus\Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            'PROTSEDURA_M' => new ReferenceField(
                'PROTSEDURA_M', 
                ProceduresPropertyValuesTable::class, 
                ['=this.PROTSEDURA_M_ID' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
